/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ClientRouteImport } from './routes/client'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LineRouteImport } from './routes/line'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StartRouteImport } from './routes/start'
import { Route as AdminKeysRouteImport } from './routes/admin_.keys'
import { Route as AdminLawRouteImport } from './routes/admin_.law'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppModuleRouteImport } from './routes/app.$module'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as ClientKeysRouteImport } from './routes/client_.keys'
import { Route as LawIndexRouteImport } from './routes/law.index'
import { Route as LawSignupRouteImport } from './routes/law.signup'
import { Route as LawTermsRouteImport } from './routes/law.terms'
import { Route as StartIndexRouteImport } from './routes/start.index'
import { Route as StartSlugRouteImport } from './routes/start.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesIdRouteImport } from './routes/api/files.$id'
import { Route as ApiLawMoyasarRouteImport } from './routes/api/law/moyasar'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiV1RequestsRouteImport } from './routes/api/v1/requests'
import { Route as ApiV1ServicesRouteImport } from './routes/api/v1/services'
import { Route as AppInviteTokenRouteImport } from './routes/app_.invite.$token'
import { Route as ClientRequestsIdRouteImport } from './routes/client_.requests.$id'
import { Route as DeskCrmViewRouteImport } from './routes/desk.crm.$view'
import { Route as DeskLawViewRouteImport } from './routes/desk.law.$view'
import { Route as DeskPayViewRouteImport } from './routes/desk.pay.$view'
import { Route as ApiRequestsIdMessagesRouteImport } from './routes/api/requests.$id.messages'
import { Route as ApiV1AdminRequestsRouteImport } from './routes/api/v1/admin/requests'
import { Route as ApiV1RequestsIdRouteImport } from './routes/api/v1/requests.$id'
import { Route as ApiV1AdminRequestsIdRouteImport } from './routes/api/v1/admin/requests.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LineRoute = LineRouteImport.update({
  id: '/line',
  path: '/line',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/admin_/keys',
  path: '/admin/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLawRoute = AdminLawRouteImport.update({
  id: '/admin_/law',
  path: '/admin/law',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const ClientKeysRoute = ClientKeysRouteImport.update({
  id: '/client_/keys',
  path: '/client/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LawIndexRoute = LawIndexRouteImport.update({
  id: '/law/',
  path: '/law/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawSignupRoute = LawSignupRouteImport.update({
  id: '/law/signup',
  path: '/law/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LawTermsRoute = LawTermsRouteImport.update({
  id: '/law/terms',
  path: '/law/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StartRoute,
} as any)
const StartSlugRoute = StartSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StartRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLawMoyasarRoute = ApiLawMoyasarRouteImport.update({
  id: '/api/law/moyasar',
  path: '/api/law/moyasar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RequestsRoute = ApiV1RequestsRouteImport.update({
  id: '/api/v1/requests',
  path: '/api/v1/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ServicesRoute = ApiV1ServicesRouteImport.update({
  id: '/api/v1/services',
  path: '/api/v1/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInviteTokenRoute = AppInviteTokenRouteImport.update({
  id: '/app_/invite/$token',
  path: '/app/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRequestsIdRoute = ClientRequestsIdRouteImport.update({
  id: '/client_/requests/$id',
  path: '/client/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskCrmViewRoute = DeskCrmViewRouteImport.update({
  id: '/desk/crm/$view',
  path: '/desk/crm/$view',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskLawViewRoute = DeskLawViewRouteImport.update({
  id: '/desk/law/$view',
  path: '/desk/law/$view',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskPayViewRoute = DeskPayViewRouteImport.update({
  id: '/desk/pay/$view',
  path: '/desk/pay/$view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsIdMessagesRoute = ApiRequestsIdMessagesRouteImport.update({
  id: '/api/requests/$id/messages',
  path: '/api/requests/$id/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminRequestsRoute = ApiV1AdminRequestsRouteImport.update({
  id: '/api/v1/admin/requests',
  path: '/api/v1/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RequestsIdRoute = ApiV1RequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1RequestsRoute,
} as any)
const ApiV1AdminRequestsIdRoute = ApiV1AdminRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1AdminRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/client': typeof ClientRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/line': typeof LineRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRouteWithChildren
  '/admin/keys': typeof AdminKeysRoute
  '/admin/law': typeof AdminLawRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/$module': typeof AppModuleRoute
  '/app/billing': typeof AppBillingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/client/keys': typeof ClientKeysRoute
  '/law/signup': typeof LawSignupRoute
  '/law/terms': typeof LawTermsRoute
  '/start/$slug': typeof StartSlugRoute
  '/app/': typeof AppIndexRoute
  '/law/': typeof LawIndexRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/law/moyasar': typeof ApiLawMoyasarRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/requests': typeof ApiV1RequestsRouteWithChildren
  '/api/v1/services': typeof ApiV1ServicesRoute
  '/app/invite/$token': typeof AppInviteTokenRoute
  '/client/requests/$id': typeof ClientRequestsIdRoute
  '/desk/crm/$view': typeof DeskCrmViewRoute
  '/desk/law/$view': typeof DeskLawViewRoute
  '/desk/pay/$view': typeof DeskPayViewRoute
  '/api/requests/$id/messages': typeof ApiRequestsIdMessagesRoute
  '/api/v1/admin/requests': typeof ApiV1AdminRequestsRouteWithChildren
  '/api/v1/requests/$id': typeof ApiV1RequestsIdRoute
  '/api/v1/admin/requests/$id': typeof ApiV1AdminRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/client': typeof ClientRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/line': typeof LineRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/law': typeof AdminLawRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/$module': typeof AppModuleRoute
  '/app/billing': typeof AppBillingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/client/keys': typeof ClientKeysRoute
  '/law/signup': typeof LawSignupRoute
  '/law/terms': typeof LawTermsRoute
  '/start/$slug': typeof StartSlugRoute
  '/app': typeof AppIndexRoute
  '/law': typeof LawIndexRoute
  '/start': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/law/moyasar': typeof ApiLawMoyasarRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/requests': typeof ApiV1RequestsRouteWithChildren
  '/api/v1/services': typeof ApiV1ServicesRoute
  '/app/invite/$token': typeof AppInviteTokenRoute
  '/client/requests/$id': typeof ClientRequestsIdRoute
  '/desk/crm/$view': typeof DeskCrmViewRoute
  '/desk/law/$view': typeof DeskLawViewRoute
  '/desk/pay/$view': typeof DeskPayViewRoute
  '/api/requests/$id/messages': typeof ApiRequestsIdMessagesRoute
  '/api/v1/admin/requests': typeof ApiV1AdminRequestsRouteWithChildren
  '/api/v1/requests/$id': typeof ApiV1RequestsIdRoute
  '/api/v1/admin/requests/$id': typeof ApiV1AdminRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/client': typeof ClientRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/line': typeof LineRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRouteWithChildren
  '/admin_/keys': typeof AdminKeysRoute
  '/admin_/law': typeof AdminLawRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/$module': typeof AppModuleRoute
  '/app/billing': typeof AppBillingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/client_/keys': typeof ClientKeysRoute
  '/law/signup': typeof LawSignupRoute
  '/law/terms': typeof LawTermsRoute
  '/start/$slug': typeof StartSlugRoute
  '/app/': typeof AppIndexRoute
  '/law/': typeof LawIndexRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/law/moyasar': typeof ApiLawMoyasarRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/requests': typeof ApiV1RequestsRouteWithChildren
  '/api/v1/services': typeof ApiV1ServicesRoute
  '/app_/invite/$token': typeof AppInviteTokenRoute
  '/client_/requests/$id': typeof ClientRequestsIdRoute
  '/desk/crm/$view': typeof DeskCrmViewRoute
  '/desk/law/$view': typeof DeskLawViewRoute
  '/desk/pay/$view': typeof DeskPayViewRoute
  '/api/requests/$id/messages': typeof ApiRequestsIdMessagesRoute
  '/api/v1/admin/requests': typeof ApiV1AdminRequestsRouteWithChildren
  '/api/v1/requests/$id': typeof ApiV1RequestsIdRoute
  '/api/v1/admin/requests/$id': typeof ApiV1AdminRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/client'
    | '/developers'
    | '/forgot-password'
    | '/line'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/admin/keys'
    | '/admin/law'
    | '/api/mcp'
    | '/app/$module'
    | '/app/billing'
    | '/app/settings'
    | '/app/team'
    | '/client/keys'
    | '/law/signup'
    | '/law/terms'
    | '/start/$slug'
    | '/app/'
    | '/law/'
    | '/start/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/law/moyasar'
    | '/api/v1/$'
    | '/api/v1/requests'
    | '/api/v1/services'
    | '/app/invite/$token'
    | '/client/requests/$id'
    | '/desk/crm/$view'
    | '/desk/law/$view'
    | '/desk/pay/$view'
    | '/api/requests/$id/messages'
    | '/api/v1/admin/requests'
    | '/api/v1/requests/$id'
    | '/api/v1/admin/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/developers'
    | '/forgot-password'
    | '/line'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/admin/keys'
    | '/admin/law'
    | '/api/mcp'
    | '/app/$module'
    | '/app/billing'
    | '/app/settings'
    | '/app/team'
    | '/client/keys'
    | '/law/signup'
    | '/law/terms'
    | '/start/$slug'
    | '/app'
    | '/law'
    | '/start'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/law/moyasar'
    | '/api/v1/$'
    | '/api/v1/requests'
    | '/api/v1/services'
    | '/app/invite/$token'
    | '/client/requests/$id'
    | '/desk/crm/$view'
    | '/desk/law/$view'
    | '/desk/pay/$view'
    | '/api/requests/$id/messages'
    | '/api/v1/admin/requests'
    | '/api/v1/requests/$id'
    | '/api/v1/admin/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/client'
    | '/developers'
    | '/forgot-password'
    | '/line'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/admin_/keys'
    | '/admin_/law'
    | '/api/mcp'
    | '/app/$module'
    | '/app/billing'
    | '/app/settings'
    | '/app/team'
    | '/client_/keys'
    | '/law/signup'
    | '/law/terms'
    | '/start/$slug'
    | '/app/'
    | '/law/'
    | '/start/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/law/moyasar'
    | '/api/v1/$'
    | '/api/v1/requests'
    | '/api/v1/services'
    | '/app_/invite/$token'
    | '/client_/requests/$id'
    | '/desk/crm/$view'
    | '/desk/law/$view'
    | '/desk/pay/$view'
    | '/api/requests/$id/messages'
    | '/api/v1/admin/requests'
    | '/api/v1/requests/$id'
    | '/api/v1/admin/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  ClientRoute: typeof ClientRoute
  DevelopersRoute: typeof DevelopersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LineRoute: typeof LineRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StartRoute: typeof StartRouteWithChildren
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLawRoute: typeof AdminLawRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ClientKeysRoute: typeof ClientKeysRoute
  LawSignupRoute: typeof LawSignupRoute
  LawTermsRoute: typeof LawTermsRoute
  LawIndexRoute: typeof LawIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
  ApiLawMoyasarRoute: typeof ApiLawMoyasarRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1RequestsRoute: typeof ApiV1RequestsRouteWithChildren
  ApiV1ServicesRoute: typeof ApiV1ServicesRoute
  AppInviteTokenRoute: typeof AppInviteTokenRoute
  ClientRequestsIdRoute: typeof ClientRequestsIdRoute
  DeskCrmViewRoute: typeof DeskCrmViewRoute
  DeskLawViewRoute: typeof DeskLawViewRoute
  DeskPayViewRoute: typeof DeskPayViewRoute
  ApiRequestsIdMessagesRoute: typeof ApiRequestsIdMessagesRoute
  ApiV1AdminRequestsRoute: typeof ApiV1AdminRequestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line': {
      id: '/line'
      path: '/line'
      fullPath: '/line'
      preLoaderRoute: typeof LineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/keys': {
      id: '/admin_/keys'
      path: '/admin/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/law': {
      id: '/admin_/law'
      path: '/admin/law'
      fullPath: '/admin/law'
      preLoaderRoute: typeof AdminLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/client_/keys': {
      id: '/client_/keys'
      path: '/client/keys'
      fullPath: '/client/keys'
      preLoaderRoute: typeof ClientKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/': {
      id: '/law/'
      path: '/law'
      fullPath: '/law/'
      preLoaderRoute: typeof LawIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/signup': {
      id: '/law/signup'
      path: '/law/signup'
      fullPath: '/law/signup'
      preLoaderRoute: typeof LawSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/terms': {
      id: '/law/terms'
      path: '/law/terms'
      fullPath: '/law/terms'
      preLoaderRoute: typeof LawTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/'
      fullPath: '/start/'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof StartRoute
    }
    '/start/$slug': {
      id: '/start/$slug'
      path: '/$slug'
      fullPath: '/start/$slug'
      preLoaderRoute: typeof StartSlugRouteImport
      parentRoute: typeof StartRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/law/moyasar': {
      id: '/api/law/moyasar'
      path: '/api/law/moyasar'
      fullPath: '/api/law/moyasar'
      preLoaderRoute: typeof ApiLawMoyasarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests': {
      id: '/api/v1/requests'
      path: '/api/v1/requests'
      fullPath: '/api/v1/requests'
      preLoaderRoute: typeof ApiV1RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/services': {
      id: '/api/v1/services'
      path: '/api/v1/services'
      fullPath: '/api/v1/services'
      preLoaderRoute: typeof ApiV1ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/invite/$token': {
      id: '/app_/invite/$token'
      path: '/app/invite/$token'
      fullPath: '/app/invite/$token'
      preLoaderRoute: typeof AppInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client_/requests/$id': {
      id: '/client_/requests/$id'
      path: '/client/requests/$id'
      fullPath: '/client/requests/$id'
      preLoaderRoute: typeof ClientRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/crm/$view': {
      id: '/desk/crm/$view'
      path: '/desk/crm/$view'
      fullPath: '/desk/crm/$view'
      preLoaderRoute: typeof DeskCrmViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/law/$view': {
      id: '/desk/law/$view'
      path: '/desk/law/$view'
      fullPath: '/desk/law/$view'
      preLoaderRoute: typeof DeskLawViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/pay/$view': {
      id: '/desk/pay/$view'
      path: '/desk/pay/$view'
      fullPath: '/desk/pay/$view'
      preLoaderRoute: typeof DeskPayViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests/$id/messages': {
      id: '/api/requests/$id/messages'
      path: '/api/requests/$id/messages'
      fullPath: '/api/requests/$id/messages'
      preLoaderRoute: typeof ApiRequestsIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/requests': {
      id: '/api/v1/admin/requests'
      path: '/api/v1/admin/requests'
      fullPath: '/api/v1/admin/requests'
      preLoaderRoute: typeof ApiV1AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests/$id': {
      id: '/api/v1/requests/$id'
      path: '/$id'
      fullPath: '/api/v1/requests/$id'
      preLoaderRoute: typeof ApiV1RequestsIdRouteImport
      parentRoute: typeof ApiV1RequestsRoute
    }
    '/api/v1/admin/requests/$id': {
      id: '/api/v1/admin/requests/$id'
      path: '/$id'
      fullPath: '/api/v1/admin/requests/$id'
      preLoaderRoute: typeof ApiV1AdminRequestsIdRouteImport
      parentRoute: typeof ApiV1AdminRequestsRoute
    }
  }
}

interface AppRouteChildren {
  AppModuleRoute: typeof AppModuleRoute
  AppBillingRoute: typeof AppBillingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleRoute: AppModuleRoute,
  AppBillingRoute: AppBillingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface StartRouteChildren {
  StartSlugRoute: typeof StartSlugRoute
  StartIndexRoute: typeof StartIndexRoute
}

const StartRouteChildren: StartRouteChildren = {
  StartSlugRoute: StartSlugRoute,
  StartIndexRoute: StartIndexRoute,
}

const StartRouteWithChildren = StartRoute._addFileChildren(StartRouteChildren)

interface ApiV1RequestsRouteChildren {
  ApiV1RequestsIdRoute: typeof ApiV1RequestsIdRoute
}

const ApiV1RequestsRouteChildren: ApiV1RequestsRouteChildren = {
  ApiV1RequestsIdRoute: ApiV1RequestsIdRoute,
}

const ApiV1RequestsRouteWithChildren = ApiV1RequestsRoute._addFileChildren(
  ApiV1RequestsRouteChildren,
)

interface ApiV1AdminRequestsRouteChildren {
  ApiV1AdminRequestsIdRoute: typeof ApiV1AdminRequestsIdRoute
}

const ApiV1AdminRequestsRouteChildren: ApiV1AdminRequestsRouteChildren = {
  ApiV1AdminRequestsIdRoute: ApiV1AdminRequestsIdRoute,
}

const ApiV1AdminRequestsRouteWithChildren =
  ApiV1AdminRequestsRoute._addFileChildren(ApiV1AdminRequestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  ClientRoute: ClientRoute,
  DevelopersRoute: DevelopersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LineRoute: LineRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StartRoute: StartRouteWithChildren,
  AdminKeysRoute: AdminKeysRoute,
  AdminLawRoute: AdminLawRoute,
  ApiMcpRoute: ApiMcpRoute,
  ClientKeysRoute: ClientKeysRoute,
  LawSignupRoute: LawSignupRoute,
  LawTermsRoute: LawTermsRoute,
  LawIndexRoute: LawIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
  ApiLawMoyasarRoute: ApiLawMoyasarRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1RequestsRoute: ApiV1RequestsRouteWithChildren,
  ApiV1ServicesRoute: ApiV1ServicesRoute,
  AppInviteTokenRoute: AppInviteTokenRoute,
  ClientRequestsIdRoute: ClientRequestsIdRoute,
  DeskCrmViewRoute: DeskCrmViewRoute,
  DeskLawViewRoute: DeskLawViewRoute,
  DeskPayViewRoute: DeskPayViewRoute,
  ApiRequestsIdMessagesRoute: ApiRequestsIdMessagesRoute,
  ApiV1AdminRequestsRoute: ApiV1AdminRequestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
